init = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  #"Blinks Number",
  #"Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  #"Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min", 
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"]

init_blinks_no_head = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

init_blinks = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"]

init_blinks_no_min_max = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median"
  ]

init_blinks_no_min_max_no_head = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  ]

left_right = [
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max"]

left = [
  "Left Pupil Diameter Mean", "Left Pupil Diameter Std",
  "Left Pupil Diameter Median", "Left Pupil Diameter Min", "Left Pupil Diameter Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  ]


right = [
  "Right Pupil Diameter Mean", "Right Pupil Diameter Std",
  "Right Pupil Diameter Median", "Right Pupil Diameter Min", "Right Pupil Diameter Max",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

left_right_average = [
  "Pupil Diameter Mean", "Pupil Diameter Std",
  "Pupil Diameter Median", "Pupil Diameter Min", "Pupil Diameter Max",
  "Blink Closing Amplitude Mean", "Blink Opening Amplitude Mean",
  "Blink Closing Speed Mean", "Blink Opening Speed Mean",
  "Blink Closing Amplitude Std", "Blink Opening Amplitude Std",
  "Blink Closing Speed Std", "Blink Opening Speed Std",
  "Blink Closing Amplitude Max", "Blink Opening Amplitude Max",
  "Blink Closing Speed Max", "Blink Opening Speed Max",
  ]

left_right_diff = [
  "Pupil Diameter Mean Diff", "Pupil Diameter Std Diff",
  "Pupil Diameter Median Diff", "Pupil Diameter Min Diff", "Pupil Diameter Max Diff",
  "Blink Closing Amplitude Mean Diff", "Blink Opening Amplitude Mean Diff",
  "Blink Closing Speed Mean Diff", "Blink Opening Speed Mean Diff",
  "Blink Closing Amplitude Std Diff", "Blink Opening Amplitude Std Diff", 
  "Blink Closing Speed Std Diff", "Blink Opening Speed Std Diff",
  "Blink Closing Amplitude Max Diff", "Blink Opening Amplitude Max Diff",
  "Blink Closing Speed Max Diff", "Blink Opening Speed Max Diff",
  ]

left_right_ratio = [
  "Pupil Diameter Mean Ratio", "Pupil Diameter Std Ratio",
  "Pupil Diameter Median Ratio", "Pupil Diameter Min Ratio", "Pupil Diameter Max Ratio",
  "Blink Closing Amplitude Mean Ratio", "Blink Opening Amplitude Mean Ratio",
  "Blink Closing Speed Mean Ratio", "Blink Opening Speed Mean Ratio",
  "Blink Closing Amplitude Std Ratio", "Blink Opening Amplitude Std Ratio",
  "Blink Closing Speed Std Ratio", "Blink Opening Speed Std Ratio",
  "Blink Closing Amplitude Max Ratio", "Blink Opening Amplitude Max Ratio",
  "Blink Closing Speed Max Ratio", "Blink Opening Speed Max Ratio",
  ]

diameter_left_right = [
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Pupil Diameter SD", "Right Pupil Diameter SD",
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
]

amplitude_left_right = ["Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Left Blink Closing Amplitude SD", "Left Blink Opening Amplitude SD", 
  "Right Blink Closing Amplitude SD", "Right Blink Opening Amplitude SD",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
]

speed_left_right = ["Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Blink Closing Speed SD", "Left Blink Opening Speed SD",
  "Right Blink Closing Speed SD", "Right Blink Opening Speed SD",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max"
  ]

saccade_duration = ["Saccades Duration Mean", "Saccades Duration SD", 
                    "Saccades Duration Median",
                    "Saccades Duration Max"
                    ]

fixation_duration = ["Fixation Duration Mean", "Fixation Duration SD",
                     "Fixation Duration Median",
                     "Fixation Duration Max"
                     ]

blink_duration =  ["Blinks Duration Mean", "Blinks Duration SD",
                   "Blinks Duration Median",
                   "Blinks Duration Min", "Blinks Duration Max"
                   ]

head_position =  ["Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
                  "Head Heading SD", "Head Pitch SD", "Head Roll SD",
                  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
                  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
                  "Head Heading Max", "Head Pitch Max", "Head Roll Max"
                  ]

init_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
 #"Blinks Number",
 #"Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
 #"Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean",
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 "Head Heading Std", "Head Pitch Std", "Head Roll Std",
 "PupilDiameter Median", "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 "Head Heading Median", "Head Pitch Median", "Head Roll Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 "Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 "Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
 #"PupilDiameter Min", 
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 "Head Heading Min", "Head Pitch Min", "Head Roll Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
 "Head Heading Max", "Head Pitch Max", "Head Roll Max"]
 
init_blinks_no_head_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
 "Fixation Duration Max",
 "Blinks Number",
 "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 "Blinks Duration Quantile25", "Blinks Duration Quantile75",
 "Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean", 
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 #"PupilDiameter Median",
 "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 #"PupilDiameter Min",
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

init_blinks_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
 "Fixation Duration Max",
 "Blinks Number",
 "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 "Blinks Duration Quantile25", "Blinks Duration Quantile75",
 "Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean", 
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 "Head Heading Std", "Head Pitch Std", "Head Roll Std",
 #"PupilDiameter Median",
 "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 "Head Heading Median", "Head Pitch Median", "Head Roll Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 "Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 "Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
 #"PupilDiameter Min",
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 "Head Heading Min", "Head Pitch Min", "Head Roll Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
 "Head Heading Max", "Head Pitch Max", "Head Roll Max"]


saccade_fixation_blinks = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max"
  ]


saccade_fixation_blinks_head = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"
  ]

blinks = [
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

blinks_quantiles = [
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  "Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]
