init = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  #"Blinks Number",
  #"Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  #"Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min", 
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"]

init_blinks_no_head = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

init_blinks = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  #"PupilDiameter Mean", 
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  #"PupilDiameter Std", 
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  #"PupilDiameter Median", 
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  #"PupilDiameter Quantile25",
  #"Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
  #"PupilDiameter Quantile75",
  #"Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  #"Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
  #"PupilDiameter Min",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  #"PupilDiameter Max", 
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"]

left_right = [
  "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Pupil Diameter Std", "Right Pupil Diameter Std",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Left Pupil Diameter Median", "Right Pupil Diameter Median",
  "Left Pupil Diameter Min", "Right Pupil Diameter Min",
  "Left Pupil Diameter Max", "Right Pupil Diameter Max",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max"]

left = [
  "Left Pupil Diameter Mean", "Left Pupil Diameter Std",
  "Left Pupil Diameter Median", "Left Pupil Diameter Min", "Left Pupil Diameter Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  ]


right = [
  "Right Pupil Diameter Mean", "Right Pupil Diameter Std",
  "Right Pupil Diameter Median", "Right Pupil Diameter Min", "Right Pupil Diameter Max",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

left_right_average = [
  "Pupil Diameter Mean", "Pupil Diameter Std",
  "Pupil Diameter Median", "Pupil Diameter Min", "Pupil Diameter Max",
  "Blink Closing Amplitude Mean", "Blink Opening Amplitude Mean",
  "Blink Closing Speed Mean", "Blink Opening Speed Mean",
  "Blink Closing Amplitude Std", "Blink Opening Amplitude Std",
  "Blink Closing Speed Std", "Blink Opening Speed Std",
  "Blink Closing Amplitude Max", "Blink Opening Amplitude Max",
  "Blink Closing Speed Max", "Blink Opening Speed Max",
  ]

left_right_diff = [
  "Pupil Diameter Mean Diff", "Pupil Diameter Std Diff",
  "Pupil Diameter Median Diff", "Pupil Diameter Min Diff", "Pupil Diameter Max Diff",
  "Blink Closing Amplitude Mean Diff", "Blink Opening Amplitude Mean Diff",
  "Blink Closing Speed Mean Diff", "Blink Opening Speed Mean Diff",
  "Blink Closing Amplitude Std Diff", "Blink Opening Amplitude Std Diff", 
  "Blink Closing Speed Std Diff", "Blink Opening Speed Std Diff",
  "Blink Closing Amplitude Max Diff", "Blink Opening Amplitude Max Diff",
  "Blink Closing Speed Max Diff", "Blink Opening Speed Max Diff",
  ]


init_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
 #"Blinks Number",
 #"Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
 #"Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean",
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 "Head Heading Std", "Head Pitch Std", "Head Roll Std",
 "PupilDiameter Median", "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 "Head Heading Median", "Head Pitch Median", "Head Roll Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 "Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 "Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
 #"PupilDiameter Min", 
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 "Head Heading Min", "Head Pitch Min", "Head Roll Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
 "Head Heading Max", "Head Pitch Max", "Head Roll Max"]
 
init_blinks_no_head_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
 "Fixation Duration Max",
 "Blinks Number",
 "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 "Blinks Duration Quantile25", "Blinks Duration Quantile75",
 "Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean", 
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 #"PupilDiameter Median",
 "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 #"PupilDiameter Min",
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

init_blinks_quantiles = ["Saccades Number",
 "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
 "Saccades Duration Quantile25", "Saccades Duration Quantile75",
 "Saccades Duration Max",
 "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
 "Fixation Duration Quantile25", "Fixation Duration Quantile75",
 "Fixation Duration Max",
 "Blinks Number",
 "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
 "Blinks Duration Quantile25", "Blinks Duration Quantile75",
 "Blinks Duration Min", "Blinks Duration Max",
 #"PupilDiameter Mean", 
 "Left Pupil Diameter Mean", "Right Pupil Diameter Mean", 
 "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
 "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
 "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
 "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
 "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
 #"PupilDiameter Std", 
 "Left Pupil Diameter Std", "Right Pupil Diameter Std",
 "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
 "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
 "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
 "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
 "Head Heading Std", "Head Pitch Std", "Head Roll Std",
 #"PupilDiameter Median",
 "Left Pupil Diameter Median", "Right Pupil Diameter Median",
 "Head Heading Median", "Head Pitch Median", "Head Roll Median",
 #"PupilDiameter Quantile25",
 "Left Pupil Diameter Quantile25", "Right Pupil Diameter Quantile25",
 #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
 #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
 #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
 #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
 "Head Heading Quantile25", "Head Pitch Quantile25", "Head Roll Quantile25",
 #"PupilDiameter Quantile75",
 "Left Pupil Diameter Quantile75", "Right Pupil Diameter Quantile75",
 #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
 #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
 #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
 #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
 "Head Heading Quantile75", "Head Pitch Quantile75", "Head Roll Quantile75",
 #"PupilDiameter Min",
 "Left Pupil Diameter Min", "Right Pupil Diameter Min",
 "Head Heading Min", "Head Pitch Min", "Head Roll Min",
 #"PupilDiameter Max", 
 "Left Pupil Diameter Max", "Right Pupil Diameter Max",
 "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
 "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
 "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
 "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
 "Head Heading Max", "Head Pitch Max", "Head Roll Max"]


importance_CHS_binary_SVC = [
  'Blink Closing Amplitude Std', 'Blink Opening Amplitude Std',
  'Blink Closing Amplitude Mean', 'Blink Opening Speed Std',
  'Blink Closing Speed Std', 'Blinks Number',
  'Saccades Duration Mean', 'Blink Opening Speed Max',
  'Blink Closing Speed Max', 'Pupil Diameter Max',
  'Blink Opening Amplitude Mean', 'Blink Closing Speed Mean',
  'Blinks Duration Median', 'Fixation Duration Std',
  'Pupil Diameter Min', 'Pupil Diameter Median',
  'Fixation Duration Max', 'Blinks Duration Max',
  'Fixation Duration Median', 'Blink Opening Speed Mean',
  'Fixation Duration Mean', 'Blinks Duration Mean',
  'Saccades Duration Max', 'Pupil Diameter Std',
  'Blink Closing Amplitude Max', 'Blinks Duration Min',
  'Saccades Duration Std', 'Saccades Duration Median',
  'Pupil Diameter Mean', 'Saccades Number',
  'Blinks Duration Std', 'Blink Opening Amplitude Max']

importance_CHS_binary_HGBC = ['Fixation Duration Median', 'Blink Closing Speed Mean',
  'Blink Closing Amplitude Mean', 'Blink Closing Speed Std',
  'Blink Closing Amplitude Std', 'Fixation Duration Max',
  'Blink Opening Speed Mean', 'Fixation Duration Mean',
  'Saccades Duration Median', 'Blink Closing Amplitude Max',
  'Blink Opening Amplitude Std', 'Pupil Diameter Mean',
  'Blinks Number', 'Blinks Duration Mean',
  'Blinks Duration Max', 'Blink Opening Speed Max',
  'Pupil Diameter Min', 'Blink Opening Speed Std',
  'Blinks Duration Min', 'Saccades Number',
  'Saccades Duration Mean', 'Saccades Duration Max',
  'Blinks Duration Median', 'Pupil Diameter Max',
  'Blink Opening Amplitude Mean', 'Pupil Diameter Std',
  'Blink Closing Speed Max', 'Blinks Duration Std',
  'Saccades Duration Std', 'Fixation Duration Std',
  'Pupil Diameter Median', 'Blink Opening Amplitude Max']

importance_CHS_3cl_SVC = ['Blinks Number', 'Blink Closing Amplitude Mean',
  'Blink Opening Speed Std', 'Blink Closing Amplitude Std',
  'Blink Closing Speed Std', 'Blink Opening Speed Max',
  'Pupil Diameter Max', 'Blink Closing Speed Max',
  'Fixation Duration Std', 'Blink Opening Speed Mean',
  'Pupil Diameter Min', 'Blinks Duration Median',
  'Blink Opening Amplitude Mean', 'Blinks Duration Max',
  'Fixation Duration Mean', 'Saccades Duration Max',
  'Saccades Duration Mean', 'Fixation Duration Max',
  'Fixation Duration Median', 'Blink Opening Amplitude Std',
  'Blinks Duration Min', 'Pupil Diameter Mean',
  'Blink Closing Amplitude Max', 'Pupil Diameter Std',
  'Saccades Duration Std', 'Saccades Number',
  'Saccades Duration Median', 'Blink Opening Amplitude Max',
  'Blink Closing Speed Mean', 'Blinks Duration Mean',
  'Pupil Diameter Median', 'Blinks Duration Std']

importance_CHS_3cl_HGBC = ['Fixation Duration Mean', 'Blink Opening Speed Mean',
  'Blink Closing Speed Mean', 'Saccades Number',
  'Saccades Duration Median', 'Blink Closing Speed Std',
  'Blink Closing Amplitude Mean', 'Blink Opening Speed Std',
  'Blink Opening Speed Max', 'Blink Closing Amplitude Std',
  'Blinks Duration Max', 'Pupil Diameter Min',
  'Blink Opening Amplitude Mean', 'Blinks Duration Min',
  'Fixation Duration Std', 'Blinks Duration Median',
  'Blink Closing Amplitude Max', 'Fixation Duration Median',
  'Saccades Duration Max', 'Blinks Number',
  'Pupil Diameter Median', 'Blink Closing Speed Max',
  'Pupil Diameter Max', 'Fixation Duration Max',
  'Pupil Diameter Std', 'Saccades Duration Mean',
  'Saccades Duration Std', 'Blink Opening Amplitude Max',
  'Blinks Duration Mean', 'Blink Opening Amplitude Std',
  'Pupil Diameter Mean', 'Blinks Duration Std']


saccade_fixation_blinks = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max"
  ]


saccade_fixation_blinks_head = ["Saccades Number",
  "Saccades Duration Mean", "Saccades Duration Std", "Saccades Duration Median",
  #"Saccades Duration Quantile25", "Saccades Duration Quantile75",
  "Saccades Duration Max",
  "Fixation Duration Mean", "Fixation Duration Std", "Fixation Duration Median",
  #"Fixation Duration Quantile25", "Fixation Duration Quantile75",
  "Fixation Duration Max",
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Head Heading Mean", "Head Pitch Mean", "Head Roll Mean",
  "Head Heading Std", "Head Pitch Std", "Head Roll Std",
  "Head Heading Median", "Head Pitch Median", "Head Roll Median",
  "Head Heading Min", "Head Pitch Min", "Head Roll Min",
  "Head Heading Max", "Head Pitch Max", "Head Roll Max"
  ]

blinks = [
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  #"Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  #"Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  #"Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  #"Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  #"Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  #"Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  #"Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  #"Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  #"Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]

blinks_quantiles = [
  "Blinks Number",
  "Blinks Duration Mean", "Blinks Duration Std", "Blinks Duration Median",
  "Blinks Duration Quantile25", "Blinks Duration Quantile75",
  "Blinks Duration Min", "Blinks Duration Max",
  "Left Blink Closing Amplitude Mean", "Left Blink Opening Amplitude Mean",
  "Left Blink Closing Speed Mean", "Left Blink Opening Speed Mean",
  "Right Blink Closing Amplitude Mean", "Right Blink Opening Amplitude Mean",
  "Right Blink Closing Speed Mean", "Right Blink Opening Speed Mean",
  "Left Blink Closing Amplitude Std", "Left Blink Opening Amplitude Std", 
  "Left Blink Closing Speed Std", "Left Blink Opening Speed Std",
  "Right Blink Closing Amplitude Std", "Right Blink Opening Amplitude Std",
  "Right Blink Closing Speed Std", "Right Blink Opening Speed Std",
  "Left Blink Closing Amplitude Quantile25", "Left Blink Opening Amplitude Quantile25",
  "Left Blink Closing Speed Quantile25", "Left Blink Opening Speed Quantile25",
  "Right Blink Closing Amplitude Quantile25", "Right Blink Opening Amplitude Quantile25",
  "Right Blink Closing Speed Quantile25", "Right Blink Opening Speed Quantile25",
  "Left Blink Closing Amplitude Quantile75", "Left Blink Opening Amplitude Quantile75",
  "Left Blink Closing Speed Quantile75", "Left Blink Opening Speed Quantile75",
  "Right Blink Closing Amplitude Quantile75", "Right Blink Opening Amplitude Quantile75",
  "Right Blink Closing Speed Quantile75", "Right Blink Opening Speed Quantile75",
  "Left Blink Closing Amplitude Max", "Left Blink Opening Amplitude Max",
  "Left Blink Closing Speed Max", "Left Blink Opening Speed Max",
  "Right Blink Closing Amplitude Max", "Right Blink Opening Amplitude Max",
  "Right Blink Closing Speed Max", "Right Blink Opening Speed Max",
  ]
